### ISSUE TITLE
Changing beacon uuid that trigers monalisa fragment

### ISSUE THREAD

**Issue by neshatgithub** [NordicSemiconductor/Android-nRF-Beacon#3]
As i can see, the monolisa fragment only trigers if the uuid of beacon is 0x0112233445566778899aabbccddeeff0

But i cannot seem to find the place where i can input other uuid s so that monalisa get triger by them too.
My app can find the beacons with no problem, but i only can have the monalisa if i program the beacon with the aforementioned uuid.
I would really appreciate it if you answer my question.

**Comment by philips77** [comment]
Hi, the app allows to add and assign an action to any nRF Beacon just by tapping it. First you have to make it advertising with UUID, major and minor you want, it can be different then the Uuid you mentioned.
If you have the nRF Beacon, you may use the Update tab to configure it. Press a button on it, which will switch it to Beacon Config mode, connect, modify Uuid, major and minor the way you want (touch the Uuid row to open a dialog where you can set one of 4 predefined uuids or type a custom one), and disconnect. The Beacon will start advertising with those values. Then go back to the first tab, click Scan, touch the Beacon and set action and triggering action.
Hope it will work :)

**Comment by neshatgithub** [comment]
Thank you for the answer,
But my beacon is not nrf beacon, it is a nrf51822 simple chip that i programmed it with nrf firmware, so when i go to the update tab of the app, all the bottons and stuff are disabled and my beacon does not have any sw1 button to enter the configure mode.
What should i do in this situation??
Thank you for your time

**Comment by philips77** [comment]
Then you may program it to advertise with UUID you want. Later just go to the first tab, add it and configure actions. Any Uuid, major and minor will work for any action and trigger.

**Comment by neshatgithub** [comment]
Gotcha! It is working, thanks alot

**Comment by philips77** [comment]
Great!
