### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by KennyGoers** [NordicSemiconductor/Android-nRF-Beacon#4]
Barely compiles and breaks in Android 8&9, I assume this is dead?

**Comment by roshanrajaratnam** [comment]
We have currently stopped updating this app since we haven't seen a lot of traction lately.

**Comment by philips77** [comment]
May I ask why do you need this app? Are you working with beacons, or just looking for a reference code?
We have other apps that we support continuously: [nRF Blinky](https://github.com/NordicSemiconductor/Android-nRF-Blinky) and [nRF Toolbox](https://github.com/NordicSemiconductor/Android-nRF-Toolbox), both of them, however, rely on scanning and connecting, not on beacon technology.

**Comment by KennyGoers** [comment]
Working with an nRF52480 and was going to possibly utilize the beacon capabilities of it. The included library, even when updated to the latest utilizes foreground services in such a way as to not allow targeting current android SDK versions.
