### ISSUE TITLE
No beacons found

### ISSUE THREAD

**Issue by igor-gorjanc** [NordicSemiconductor/Android-nRF-Beacon#5]
Running ble_app_beacon on PCA10056 but nRF Beacon finds no beacons. On the other hand nRF Connect displays the same beacon properly.
Seems to be a major bug.

[Samsung Galaxy S7, Android 8.0, PCA10056, nRF SDK 15.2]

**Comment by philips77** [comment]
Hi, the app scans for 'Nordic beacons', they are similar to iBeacons, but advertise with Nordic company id instead of Apple's. If you're using the nRF beacon kit from Nordic they by default advertise with such.
Also, unfortunately we no longer maintain this app.
