### ISSUE TITLE
Beacon is not visible

### ISSUE THREAD

**Issue by Paveldeg** [NordicSemiconductor/Android-nRF-Beacon#7]
Android 8, the app cannot find beacon. Yet I can see BLE working and connect via other apps.
Is something wrong with the app or the beacon firmware code? Could you provide working Arduino beacon example?

**Comment by roshanrajaratnam** [comment]
Hi, this app hasn't been updated in 4 years and is nearly deprecated. This could be the requirement for location services which is not requested for in the App. You might want to go in to nRF Beacon app settings in the Android Settings to see if you could grant location permission and try again. Pretty sure this is something to do with the app itself and unfortunately we don't have examples for Arduino, this you might have to build yourself.

**Comment by Paveldeg** [comment]
OK. So you guys selling the chip, but decided not to maintain an app demonstrating its functions? Does beacon even work in nRF52840? 
Your "support" is sure way to loose customers.

**Comment by roshanrajaratnam** [comment]
The reason for not maintaining this app is because there has been very low user interest. You can use nRF Connect for this, if you download the nRF 5 sdk you can find beacon examples for all chips that we support. Hope this helps and thank you for your valuable feedback.
