### ISSUE TITLE
Unable to solve gradle issue

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-nRF-Beacon#8]
Unable to solve this issue,
its not getting solved.
Please provide some guidance.

21:40	Gradle sync failed: Unsupported method: SyncIssue.getMultiLineMessage().
			The version of Gradle you connect to does not support that method.
			To resolve the problem you can change/upgrade the target version of Gradle you connect to.
			Alternatively, you can ignore this exception and read other information from the model.
			Consult IDE log for more details (Help | Show Log) (7 s 428 ms)

**Comment by philips77** [comment]
Migrate the project to latest Android Studio and Gradle. Perhaps you'll need to modify the *build.gradle* file.
Sorry, but this repo is already 5 years old and no longer maintained. For our reference code, please check [nRF Blinky](https://github.com/NordicSemiconductor/Android-nRF-Blinky).
